name: find_my_rent
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: ^1.1.2 
  pin_code_fields: ^8.0.1
  lottie: ^3.1.0
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  lucide_icons_flutter: ^3.1.9
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/login_background.jpg
    - assets/images/logo.png
    - assets/images/groundshakers logo.png
    - assets/animations/success.json
    - assets/images/
   

  fonts:

    - family: Clarendon
      fonts:
        - asset: assets/fonts/Clarendon.otf
        - asset: assets/fonts/clarendon-bold.otf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

